server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/dj_party?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1

  web:
    resources:
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  redis:
    host: 127.0.0.1
    port: 6379
#    password: a123456
    database: 10
logging:
  config: classpath:logback/logback-dev.xml
elastic:
  address: http://127.0.0.1:9200

localFile:
  saveUrl: /vdb/projectFile/uploadfile/tempfile/
  deleteUrl: /vdb/projectFile/uploadfile
